### ISSUE TITLE
cast streaming of the card gives black/blank panel

### ISSUE THREAD

**Issue by jurgenweber** [Makin-Things/bom-radar-card#19]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser
- [x] I installed using HACS (leave unchecked for manual installs)

**Release with the issue:**

v1.6.0

**Last working release (if known):**

**Browser and Operating System:**
Chrome/OSX

**Card Config (click Show Code Editor and copy paste your config, remove a few of the least significant digits of your lat/lon to avoid posting you exact home address):**

```
  - title: Weather
    path: weather
    panel: true
    theme: dark
    cards:
      - type: horizontal-stack
        title: weather
        cards:
          - type: weather-forecast
            name: hourly
            entity: weather.kariong_hourly
          - type: weather-forecast
            name: daily
            entity: weather.kariong
          - type: 'custom:bom-radar-card'
            frame_count: 10
            center_latitude: -33.430999
            center_longitude: 151.287258
            show_marker: true
            show_range: true
            zoom_level: 10
```

**Description of problem:**

When I cast this onto my Chrome Cast/TV I only get a black/blank pane. I have given you the full config of the lovelace view that I cast. The weather cards are handled using the bureau_of_meteorology custom component.

**Additional information:**
Here is also the script I use to cast

```
cast_weather_living_tv:
  alias: "Show current weather on the living room tv"
  sequence:
    - data:
        dashboard_path: lovelace-cast
        entity_id: media_player.living_tv
        view_path: weather
      service: cast.show_lovelace_view
```

Love your work! I was sad when the old integration was removed due to scraping but now that I have found this, amazing.
